CREATE DATABASE IF NOT EXISTS library_management_db;
USE library_management_system;
SHOW DATABASES;
SHOW TABLES;
SELECT * FROM authors;
SELECT * FROM books;
SELECT * FROM user_profiles;
SELECT * FROM user_profile_interests;
DELETE FROM books;
DELETE FROM authors;
DELETE FROM user_profile_interests;
DELETE FROM user_profiles;
ALTER TABLE books AUTO_INCREMENT = 1;
ALTER TABLE authors AUTO_INCREMENT = 1;
ALTER TABLE user_profiles AUTO_INCREMENT = 1;
DESC authors;
DESC books;
DESC user_profiles;
DESC user_profile_interests;